spring:
  application.name: pill-buddy
  profiles.include: db
  jpa:
    properties.hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
    hibernate.ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

sms:
  api-key: ${API_KEY}
  api-secret-key: ${API_SECRET}
  domain: https://api.coolsms.co.kr
  from-number: 01040765951
